import './style.css';
import { initializeApp } from 'firebase/app';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'firebase/auth';
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, query, orderBy, serverTimestamp } from 'firebase/firestore';

const firebaseConfig={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const firebaseApp=initializeApp(firebaseConfig);const auth=getAuth(firebaseApp);const db=getFirestore(firebaseApp);const app=document.querySelector('#app');
const state={page:'home',expenses:[],categories:[],recurring:[],user:null,unsubs:[]};
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n||0);const monthNow=()=>new Date().toISOString().slice(0,7);const uid=()=>state.user.uid;const coll=n=>collection(db,'users',uid(),n);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const icon=name=>({home:'⌂',expenses:'↕',analysis:'◔',categories:'⊞',recurring:'↻'}[name]||'•');const title=()=>({home:'Casa sotto controllo',expenses:'Spese',analysis:'Analisi',categories:'Categorie',recurring:'Ricorrenti'}[state.page]);const label=p=>({home:'Home',expenses:'Spese',analysis:'Analisi',categories:'Categorie',recurring:'Ricorrenti'}[p]);
function render(){if(!state.user)return renderAuth();const m=monthNow(),monthExpenses=state.expenses.filter(e=>e.month===m),recurring=state.recurring.filter(r=>r.active),total=monthExpenses.reduce((s,e)=>s+Number(e.amount),0)+recurring.reduce((s,r)=>s+Number(r.amount),0);app.innerHTML=`<div class="shell"><header><div><span class="eyebrow">NIDO</span><h1>${title()}</h1></div><button class="avatar" onclick="window.nidoLogout()">${esc((state.user.email||'N')[0].toUpperCase())}</button></header><main>${pageContent(total,monthExpenses,recurring)}</main><nav>${['home','expenses','analysis','categories','recurring'].map(p=>`<button class="${state.page===p?'active':''}" onclick="window.nidoPage('${p}')"><span>${icon(p)}</span>${label(p)}</button>`).join('')}</nav></div>`}
function pageContent(total,ex,recs){if(state.page==='home'){const previous=state.expenses.filter(e=>e.month===previousMonth()).reduce((s,e)=>s+Number(e.amount),0)+recs.reduce((s,r)=>s+Number(r.amount),0);const diff=total-previous;return `<section class="hero"><p>${new Date().toLocaleDateString('it-IT',{month:'long',year:'numeric'})}</p><strong>${euro(total)}</strong><span>spese del mese</span></section><div class="compare ${diff>0?'up':'down'}"><span>Rispetto a ${new Date(Date.now()-31557600000).toLocaleDateString('it-IT',{month:'long',year:'numeric'})}</span><b>${diff>0?'↑':'↓'} ${euro(Math.abs(diff))}</b></div><div class="grid"><article><span>Media mensile</span><b>${euro(average())}</b></article><article><span>Ricorrenti</span><b>${euro(recs.reduce((s,r)=>s+Number(r.amount),0))}</b></article></div><section class="card"><div class="section-head"><h2>Categorie</h2><button onclick="window.nidoPage('analysis')">Vedi analisi</button></div>${categoryBars(ex.concat(recs))}</section><button class="primary big" onclick="window.nidoAdd()">＋ Aggiungi spesa</button>`}
if(state.page==='expenses')return `<div class="toolbar"><input id="search" placeholder="Cerca una spesa…" oninput="window.nidoSearch()"/><button onclick="window.nidoAdd()">＋</button></div><section id="expenseList" class="list">${expenseList(state.expenses)}</section>`;
if(state.page==='analysis')return `<section class="card"><h2>Questo anno</h2><div class="big-number">${euro(annual())}</div><div class="bars">${monthlyBars()}</div></section><section class="card"><h2>Per categoria</h2>${categoryBars(state.expenses)}</section>`;
if(state.page==='categories')return `<section class="card"><div class="section-head"><h2>Categorie</h2><button onclick="window.nidoCategory()">＋</button></div>${state.categories.map(c=>`<div class="row"><span class="cat-icon">${esc(c.icon||'•')}</span><div><b>${esc(c.name)}</b><small>${(c.subcategories||[]).map(esc).join(' · ')||'Nessuna sottocategoria'}</small></div><button onclick="window.nidoEditCategory('${c.id}')">⋯</button></div>`).join('')||'<p class="muted">Crea la tua prima categoria.</p>'}</section>`;
return `<section class="card"><div class="section-head"><h2>Spese ricorrenti</h2><button onclick="window.nidoRecurring()">＋</button></div><p class="muted">Sono incluse automaticamente nel totale di ogni mese.</p>${recs.map(r=>`<div class="row"><span class="cat-icon">↻</span><div><b>${esc(r.description)}</b><small>${categoryName(r.categoryId)}${r.subcategory?' · '+esc(r.subcategory):''}</small></div><strong>${euro(r.amount)}</strong><button onclick="window.nidoEditRecurring('${r.id}')">⋯</button></div>`).join('')||'<p class="muted">Nessuna ricorrente.</p>'}</section>`}
function previousMonth(){const d=new Date();d.setFullYear(d.getFullYear()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}function average(){const months=new Set(state.expenses.map(e=>e.month));const total=state.expenses.reduce((s,e)=>s+Number(e.amount),0)+state.recurring.reduce((s,r)=>s+Number(r.amount),0)*12;return total/Math.max(12,months.size)}function annual(){const y=String(new Date().getFullYear());return state.expenses.filter(e=>e.month?.startsWith(y)).reduce((s,e)=>s+Number(e.amount),0)+state.recurring.filter(r=>r.active).reduce((s,r)=>s+Number(r.amount),0)*12}function categoryName(id){return state.categories.find(c=>c.id===id)?.name||'Senza categoria'}
function categoryBars(items){const sums={};items.forEach(e=>{const k=categoryName(e.categoryId);sums[k]=(sums[k]||0)+Number(e.amount)});const max=Math.max(...Object.values(sums),1);return Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><b>${euro(v)}</b><i><em style="width:${v/max*100}%"></em></i></div>`).join('')||'<p class="muted">Nessuna spesa ancora.</p>'}
function monthlyBars(){const y=new Date().getFullYear();return [...Array(12)].map((_,i)=>{const v=state.expenses.filter(e=>e.month===`${y}-${String(i+1).padStart(2,'0')}`).reduce((s,e)=>s+Number(e.amount),0);return `<div class="month-bar"><i style="height:${Math.min(90,v/Math.max(1,annual()/12)*35)}px"></i><span>${i+1}</span></div>`}).join('')}
function expenseList(items){return [...items].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(e=>`<div class="expense" data-text="${esc((e.description+' '+e.note+' '+categoryName(e.categoryId)).toLowerCase())}"><div><span class="date">${esc(e.month||'')}</span><b>${esc(e.description)}</b><small>${categoryName(e.categoryId)}${e.subcategory?' · '+esc(e.subcategory):''}</small></div><strong>${euro(e.amount)}</strong><button onclick="window.nidoEditExpense('${e.id}')">⋯</button></div>`).join('')||'<div class="empty">Nessuna spesa.</div>'}
function renderAuth(){app.innerHTML=`<div class="auth"><div class="brand">NIDO</div><h1>Le spese di casa,<br/>finalmente semplici.</h1><p>Accedi per tenere tutto sotto controllo.</p><form id="authForm"><input type="email" id="email" placeholder="Email" required/><input type="password" id="password" placeholder="Password" minlength="6" required/><button class="primary" type="submit">Accedi</button><button type="button" class="secondary" onclick="window.nidoSignup()">Crea account</button><div id="authError"></div></form></div>`;document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(err){document.querySelector('#authError').textContent=err.message}}}
async function signup(){try{await createUserWithEmailAndPassword(auth,email.value,password.value)}catch(err){document.querySelector('#authError').textContent=err.message}}function modal(html){const d=document.createElement('div');d.className='modal-wrap';d.innerHTML=`<div class="modal">${html}</div>`;app.appendChild(d);return d}
const categoryOptions=selected=>state.categories.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('');
window.nidoAdd=()=>{const d=modal(`<h2>Aggiungi spesa</h2><form><input id="amount" type="number" step="0.01" min="0" placeholder="Importo €" required/><select id="categoryId" required>${categoryOptions()}</select><input id="subcategory" placeholder="Sottocategoria"/><input id="description" placeholder="Descrizione" required/><textarea id="note" placeholder="Nota (facoltativa)"></textarea><input id="month" type="month" value="${monthNow()}" required/><button class="primary">Salva</button><button type="button" class="secondary" onclick="this.closest('.modal-wrap').remove()">Annulla</button></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();await addDoc(coll('expenses'),{amount:Number(amount.value),month:month.value,categoryId:categoryId.value,subcategory:subcategory.value,description:description.value,note:note.value,createdAt:serverTimestamp()});d.remove()}}
window.nidoEditExpense=id=>{const e=state.expenses.find(x=>x.id===id);const d=modal(`<h2>Modifica spesa</h2><form><input id="amount" type="number" step="0.01" min="0" value="${e.amount}" required/><select id="categoryId" required>${categoryOptions(e.categoryId)}</select><input id="subcategory" value="${esc(e.subcategory)}"/><input id="description" value="${esc(e.description)}" required/><textarea id="note">${esc(e.note)}</textarea><input id="month" type="month" value="${e.month}" required/><button class="primary">Salva</button><button type="button" class="danger" onclick="window.nidoDeleteExpense('${id}')">Elimina</button></form>`);d.querySelector('form').onsubmit=async x=>{x.preventDefault();await updateDoc(doc(db,'users',uid(),'expenses',id),{amount:Number(amount.value),month:month.value,categoryId:categoryId.value,subcategory:subcategory.value,description:description.value,note:note.value});d.remove()}}
window.nidoDeleteExpense=async id=>{if(confirm('Eliminare questa spesa?')){await deleteDoc(doc(db,'users',uid(),'expenses',id));document.querySelector('.modal-wrap')?.remove()}};window.nidoCategory=()=>categoryModal();window.nidoEditCategory=id=>categoryModal(state.categories.find(c=>c.id===id));
function categoryModal(c={}){const d=modal(`<h2>${c.id?'Modifica':'Nuova'} categoria</h2><form><input id="name" value="${esc(c.name)}" placeholder="Nome" required/><input id="icon" value="${esc(c.icon||'◉')}" placeholder="Icona"/><input id="subs" value="${esc((c.subcategories||[]).join(', '))}" placeholder="Sottocategorie, separate da virgola"/><button class="primary">Salva</button>${c.id?'<button type="button" class="danger" id="del">Elimina</button>':''}</form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const data={name:name.value,icon:icon.value,subcategories:subs.value.split(',').map(s=>s.trim()).filter(Boolean)};c.id?await updateDoc(doc(db,'users',uid(),'categories',c.id),data):await addDoc(coll('categories'),{...data,createdAt:serverTimestamp()});d.remove()};d.querySelector('#del')?.addEventListener('click',async()=>{if(confirm('Eliminare categoria?')){await deleteDoc(doc(db,'users',uid(),'categories',c.id));d.remove()}})}
window.nidoRecurring=()=>recurringModal();window.nidoEditRecurring=id=>recurringModal(state.recurring.find(x=>x.id===id));function recurringModal(r={}){const d=modal(`<h2>${r.id?'Modifica':'Nuova'} ricorrente</h2><form><input id="amount" type="number" step="0.01" min="0" value="${r.amount||''}" placeholder="Importo mensile €" required/><select id="categoryId" required>${categoryOptions(r.categoryId)}</select><input id="subcategory" value="${esc(r.subcategory)}" placeholder="Sottocategoria"/><input id="description" value="${esc(r.description)}" placeholder="Descrizione" required/><label class="check"><input id="active" type="checkbox" ${r.id?(r.active!==false?'checked':''): 'checked'}/> Attiva</label><button class="primary">Salva</button>${r.id?'<button type="button" class="danger" id="del">Elimina</button>':''}</form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const data={amount:Number(amount.value),categoryId:categoryId.value,subcategory:subcategory.value,description:description.value,active:active.checked};r.id?await updateDoc(doc(db,'users',uid(),'recurring',r.id),data):await addDoc(coll('recurring'),{...data,createdAt:serverTimestamp()});d.remove()};d.querySelector('#del')?.addEventListener('click',async()=>{if(confirm('Eliminare ricorrente?')){await deleteDoc(doc(db,'users',uid(),'recurring',r.id));d.remove()}})}
window.nidoPage=p=>{state.page=p;render()};window.nidoLogout=()=>signOut(auth);window.nidoSignup=signup;window.nidoSearch=()=>{const q=document.querySelector('#search').value.toLowerCase();document.querySelectorAll('.expense').forEach(x=>x.style.display=x.dataset.text.includes(q)?'':'none')};
onAuthStateChanged(auth,user=>{state.user=user;if(user){state.unsubs.forEach(f=>f());state.unsubs=[onSnapshot(query(coll('expenses'),orderBy('createdAt','desc')),s=>{state.expenses=s.docs.map(d=>({id:d.id,...d.data()}));render()}),onSnapshot(coll('categories'),s=>{state.categories=s.docs.map(d=>({id:d.id,...d.data()}));render()}),onSnapshot(coll('recurring'),s=>{state.recurring=s.docs.map(d=>({id:d.id,...d.data()}));render()})]}render()});render();
